version: '3.9'



services:
    django:
        build: .
        container_name: django_t
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - redis
    celery:
        build: .
        command: celery -A core worker -l INFO
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        volumes:
            - .:/usr/src/app/
        depends_on:
            - django
            - redis
    celery_beat:
        build: .
        command: celery -A core beat -l INFO
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        volumes:
            - .:/usr/src/app/
        depends_on:
            - django
            - redis
            - celery
    redis:
        image: "redis:alpine"
        ports:
            - '6379'
